### ISSUE TITLE
dev-java/openjdk missing openjdk-16.env.sh

### ISSUE THREAD

**Issue by Putrefalcis** [Hello71/gentoo-overlay#2]
The latest version bump to openjdk-16 is looking for openjdk-16.env.sh but only openjdk-15.env.sh is present

```
 * ERROR: dev-java/openjdk-bin-16.0.1_p9::alxu failed (install phase):
 *   Unable to find the env file: /var/tmp/portage/dev-java/openjdk-bin-16.0.1_p9/files/openjdk-bin-16.env.sh
```

**Comment by Hello71** [comment]
sorry, fixed now. i really should make a script for bumping openjdk (or maybe build with -O0?)...
